services:
    _defaults:
        autoconfigure: true
        autowire: true
        bind:
            $profilesMap:
                github: Sigwin\Ariadne\Bridge\Github\GithubProfile
                gitlab: Sigwin\Ariadne\Bridge\Gitlab\GitlabProfile

    Sigwin\Ariadne\:
        resource: ../src

