framework:
    cache:
        directory: "%env(ariadne_cache_dir:ARIADNE_CACHE_DIR)%"

services:
    _defaults:
        autoconfigure: true
        autowire: true
        bind:
            $profilesMap:
                github: Sigwin\Ariadne\Bridge\Github\GithubProfile
                gitlab: Sigwin\Ariadne\Bridge\Gitlab\GitlabProfile

    Sigwin\Ariadne\:
        resource: ../src

    Sigwin\Ariadne\EnvironmentResolver:
        $cache: "%env(default::XDG_CACHE_HOME)%"
        $config: "%env(default::XDG_CONFIG_HOME)%"
        $home: "%env(default::HOME)%"

