services:
    _defaults:
        autoconfigure: true
        autowire: true
        bind:
            $clientsMap:
                github: Sigwin\Ariadne\Bridge\Github\GithubClient
                gitlab: Sigwin\Ariadne\Bridge\Gitlab\GitlabClient

    Sigwin\Ariadne\:
        resource: ../src

