imports:
    - {resource: parameters.yaml}

services:
    _defaults:
        autoconfigure: true
        autowire: true

    Sigwin\Ariadne\:
        resource: ../src

    Gitlab\Client:
        factory: [Gitlab\Client, createWithHttpClient]
        calls:
            - [authenticate, ['%sigwin_ariadne.gitlab.token%', http_token]]
